// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Queue.Infrastructure.Persistence.Database;

#nullable disable

namespace Queue.Infrastructure.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20230327183737_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Queue.Domain.Abstract.Person", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Model.DayOfTheWeek", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("NameOfTheWeek")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayOfTheWeek");
                });

            modelBuilder.Entity("Queue.Domain.Model.Job", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Queue.Domain.Model.Order", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<decimal>("ClientId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("QueueStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("QueueTimes")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ServiceId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<decimal>("WorkerId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Model.Schedule", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<DateTime>("EndOfWork")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<decimal?>("RestDayId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("StartOfWork")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestDayId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Queue.Domain.Model.Service", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Model.WorkerSkills", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<decimal>("ServiceID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("WorkerID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceID");

                    b.HasIndex("WorkerID");

                    b.ToTable("WorkerSkills", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Model.Client", b =>
                {
                    b.HasBaseType("Queue.Domain.Abstract.Person");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Model.Worker", b =>
                {
                    b.HasBaseType("Queue.Domain.Abstract.Person");

                    b.Property<decimal?>("JobId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ScheduleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasIndex("JobId");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasFilter("[ScheduleId] IS NOT NULL");

                    b.ToTable("Worker", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Model.Order", b =>
                {
                    b.HasOne("Queue.Domain.Model.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Queue.Domain.Model.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Queue.Domain.Model.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Queue.Domain.Model.Schedule", b =>
                {
                    b.HasOne("Queue.Domain.Model.DayOfTheWeek", "RestDay")
                        .WithMany()
                        .HasForeignKey("RestDayId");

                    b.Navigation("RestDay");
                });

            modelBuilder.Entity("Queue.Domain.Model.WorkerSkills", b =>
                {
                    b.HasOne("Queue.Domain.Model.Service", "Services")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Queue.Domain.Model.Worker", "Workers")
                        .WithMany()
                        .HasForeignKey("WorkerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Services");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("Queue.Domain.Model.Client", b =>
                {
                    b.HasOne("Queue.Domain.Abstract.Person", null)
                        .WithOne()
                        .HasForeignKey("Queue.Domain.Model.Client", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Queue.Domain.Model.Worker", b =>
                {
                    b.HasOne("Queue.Domain.Abstract.Person", null)
                        .WithOne()
                        .HasForeignKey("Queue.Domain.Model.Worker", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Queue.Domain.Model.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("Queue.Domain.Model.Schedule", "Schedule")
                        .WithOne("Worker")
                        .HasForeignKey("Queue.Domain.Model.Worker", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Queue.Domain.Model.Schedule", b =>
                {
                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
